update to server version 2.2

diff --git a/server/cgi/safewebdrop-functions b/server/cgi/safewebdrop-functions
--- a/server/cgi/safewebdrop-functions
+++ b/server/cgi/safewebdrop-functions
@@ -2,8 +2,9 @@
 # function module for SafeWebdrop (server) #
 ############################################
 
-DEST="/home/safewebdrop"
+DEST=""
 PUBKEY=""
+LOG=""
 
 #----------------------------------------------------#
 function safewebdrophash {
@@ -34,6 +35,7 @@ function check_userid {
 	             exit 3
 	        fi
            else
+	        # no such user $1
 	        exit 1
            fi
      else
@@ -105,11 +107,16 @@ function verify_request {
 	            cleansig
 	            exit 4
 	       fi
+          else
+	       # no request
+	       exit 2
           fi 
      else
+          # verification error
           cleansig
           exit 3
      fi
+     # request verified corrctly
 }
 
 function check_user_and_challenge {
diff --git a/server/cgi/safewebdropgettarball b/server/cgi/safewebdropgettarball
--- a/server/cgi/safewebdropgettarball
+++ b/server/cgi/safewebdropgettarball
@@ -2,13 +2,13 @@
 
 ##############################################################################
 # This file is part of the CRYPTO BONE
-# File     : safewebdroppermission   (server) 
-# Version  : 2.0 (ALL-IN-ONE)
+# File     : safewebdropgettarball  (server) 
+# Version  : 2.2 (ALL-IN-ONE)
 # License  : BSD-3-Clause
-# Date     : 19 Apr 2025
+# Date     : 28 May 2026
 # Contact  : Please send enquiries and bug-reports to innovation@senderek.ie
 #
-# Copyright (c) 2015-2025
+# Copyright (c) 2015-2026
 #	Ralf Senderek, Ireland.  All rights reserved. (https://senderek.ie)
 #
 # Redistribution and use in source and binary forms, with or without
@@ -38,11 +38,20 @@
 #----------------------------------------------------#
 # load functions and global variables
 . ./safewebdrop-functions
+#----------------------------------------------------#
+
+# import system config file
+if [[ -s /etc/safewebdrop.config ]] ; then
+    . /etc/safewebdrop.config
+fi
 
 function clean {
-     rm -f ${FILE} 2> /dev/null
-     rm -f ${SIGNED} 2> /dev/null
-     rm -f ${VERIFIED} 2> /dev/null
+     rm -f ${DEST}/${ID}/attachrequest 2> /dev/null
+     rm -f ${DEST}/${ID}/received 2> /dev/null
+     rm -f ${DEST}/${ID}/signedrequest 2> /dev/null
+     rm -f ${DEST}/${ID}/verified 2> /dev/null
+     rm -f ${DEST}/${ID}/delete 2> /dev/null
+     rm -f ${DEST}/${ID}/tarfiles 2> /dev/null
 }
 #----------------------------------------------------#
 
@@ -52,7 +61,7 @@ function clean {
 
 ID=""
 REQ=""
-# extract ID, REQ and HASHSIG
+# extract ID  and REQ
 OLDIFS="${IFS}"
 IFS=\&
 set -- $QUERY_STRING 
@@ -68,33 +77,28 @@ IP=$REMOTE_ADDR
 check_userid ${ID}
 
 LOG=${DEST}/${ID}/log
+FILE=${DEST}/${ID}/attachrequest
+TARFILES=${DEST}/${ID}/tarfiles
 
-# make sure the contact directory exists and is accessible for the webserver
-if [[ ! -d  ${DEST}/${ID}/contacts ]] ; then
-     /usr/bin/mkdir -p ${DEST}/${ID}/contacts
-     /usr/bin/chown apache ${DEST}/${ID}/contacts
-fi
+# request=NEW or it consists of signed data
 
-FILE=${DEST}/${ID}/permission   # to save the state for this request
-     
-log "--- permission request ---"
-# request = ALLOW or it consists of signed data
-
-if [[ ${REQ} = "ALLOW" ]]; then
+if [[ ${REQ} = "NEW" ]]; then
      # phase 1
- 
- log "create a new safewebdrop request"
+     log "--- tarball request"
      generate_challenge
      return_challenge
+     exit 0
+fi
 
-else
+if [[ ${REQ} != "NEW" ]] && [[ ${REQ} ]] ; then
+
      # phase 2
-     log "signed request"
+     log "signed tarball request"
      # load the stored credentials
      if [[ -r ${FILE} ]] ; then
           .  ${FILE}
      fi
-     
+
      # check if new request has same ADDR
      if [[ ${IP} != ${ADDR}  ]] ; then
          # dismiss this request
@@ -106,49 +110,58 @@ else
      verify_request
      # signature is OK
 
+     # split the request
 
-     # split the  request
      OLDIFS="${IFS}"
      IFS=\:
      set -- ${REQ} 
-     WCHL=$1
-     CONTACT=$2
-     CONTACTHASH=$3
+     WID=$1
+     WCHL=$2
+     WREQ=$3
+     # WREQ is "ALL" or "hash(tarball)"
      IFS=${OLDIFS}
 
-     if [[  ${WCHL} != ${CHALLENGE} ]]  ; then
-          # request failed
-	  log "request ${WREQ} failed $(/usr/bin/date +'%x %X')"
-          clean
-	  exit 3
-     fi
-     
-     # safe the hash 
-     if (( ${#CONTACTHASH} == 64 )) ; then
-          /usr/bin/echo -n ${CONTACTHASH} > ${DEST}/${ID}/contacts/${CONTACT}.allow
-          /usr/bin/echo -n "OK"
-          log "--- end permission request ---"
+     check_user_and_challenge
+
+     if [[ ${WREQ} = "ALL" ]] ; then
+          # check if webdrops and/or attachments are present
+	  LIST=$(/usr/bin/ls ${DEST}/${ID}/file-* ${DEST}/${ID}/drop-* 2>/dev/null)
+	  if (( ${#LIST} == 0 )) ; then
+	      # no safewebdrops or attachments for this user
+	      log "EMPTY"
+              /usr/bin/echo -n EMPTY
+	      clean
+	      exit 0
+	  else
+	      # store the list for deletion
+	      RES=$(cd ${DEST}/${ID}; /usr/bin/ls drop-* file-* 2>/dev/null)
+	      /usr/bin/echo -n $RES > ${DEST}/${ID}/deletefiles
+              RES=$(cd ${DEST}/${ID}; /usr/bin/tar czf ${TARFILES} $(/usr/bin/cat ${DEST}/${ID}/deletefiles) 2>&1 )
+              if (( $? == 0 )) ; then
+	           HASH=$(filehash ${TARFILES})
+	           /usr/bin/echo -n "HASH=${HASH}" >> $FILE 
+	           /usr/bin/cat ${TARFILES}
+		   log "tarball sent back ..."
+	           exit 0
+	      else
+	           log "Error: building a tarball."
+	      fi
+	  fi
+    
      else
-          /usr/bin/echo -n "failed"
-	  clean
-	  exit 3
+          # check hash(tarball)
+	  if [[ ${WREQ} = ${HASH} ]] ; then
+	       # remove transferred files
+               RES=$(cd ${DEST}/${ID}; /usr/bin/rm -f $(/usr/bin/cat ${DEST}/${ID}/deletefiles) > /dev/null 2> /dev/null)
+	       clean
+	       log "transferred tarfile deleted"
+	       /usr/bin/echo -n "OK"
+	  else
+	       clean
+               /usr/bin/echo -n "hash failed."
+	       log "hash failed - files remain" 
+	  fi
      fi
+     exit 0 
 fi     
-
-# now check if a cross server request is already stored
-if [[ -s ${DEST}/${ID}/contacts/${CONTACT}.request ]] ; then
-     /usr/bin/diff ${DEST}/${ID}/contacts/${CONTACT}.allow ${DEST}/${ID}/contacts/${CONTACT}.request 2>/dev/null >/dev/null
-     if (( $? == 0 )) ; then
-          log "checking the allow file ${CONTACT}.allow"
-          log "request and allow matches for ${CONTACT}. PUBKEY registered!"
-          /usr/bin/mv ${DEST}/${ID}/contacts/${CONTACT}.pubkey.pending ${DEST}/${ID}/contacts/${CONTACT}.pubkey.pem
-          /usr/bin/rm -f ${DEST}/${ID}/contacts/${CONTACT}.allow ${DEST}/${ID}/contacts/${CONTACT}.request 2>/dev/null >/dev/null
-     else
-          log "request and allow DO NOT MATCH for ${CONTACT}."
-     fi
-else
-     log "no request for ${CONTACT} yet"
-fi
-
-clean
 exit 0
diff --git a/server/cgi/safewebdropregistration b/server/cgi/safewebdropregistration
--- a/server/cgi/safewebdropregistration
+++ b/server/cgi/safewebdropregistration
@@ -3,12 +3,12 @@
 ##############################################################################
 # This file is part of the CRYPTO BONE
 # File     : safewebdropregistration (server) 
-# Version  : 2.0 (ALL-IN-ONE)
+# Version  : 2.2 (ALL-IN-ONE)
 # License  : BSD-3-Clause
-# Date     : 19 Apr 2025
+# Date     : 29 May 2026
 # Contact  : Please send enquiries and bug-reports to innovation@senderek.ie
 #
-# Copyright (c) 2015-2025
+# Copyright (c) 2015-2026
 #	Ralf Senderek, Ireland.  All rights reserved. (https://senderek.ie)
 #
 # Redistribution and use in source and binary forms, with or without
@@ -41,13 +41,23 @@ ID=""
 REQ=""
 KEY=""
 
+
 #----------------------------------------------------#
 # load functions and global variables
 . ./safewebdrop-functions
 #----------------------------------------------------#
 
-DEST="/home/safewebdrop/admin"
+# import system config file
+if [[ -s /etc/safewebdrop.config ]] ; then
+    . /etc/safewebdrop.config
+else
+     DEST="/var/safewebdrop"
+fi
+
+
+DEST="${DEST}/admin"
 LOG=${DEST}/log
+
 
 if [[ ! -d ${DEST} ]] ; then
      /usr/bin/echo "CONFIGURATION ERROR: the admin directory ${DEST} does not exist." | mail ${ADMINNAME}
@@ -69,7 +79,7 @@ HASHSIG=$3
 KEY=$4
 IFS=${OLDIFS}
 
-# get the IP
+# get the client's IP
 IP=$REMOTE_ADDR
 
 if [[ ! ${ID} ]]; then
@@ -77,7 +87,9 @@ if [[ ! ${ID} ]]; then
     log "No user ID in registration. Exiting ..."
     exit 2 
 fi
-if [[ ${ID} = admin* ]] ;then 
+if [[ ${ID} = admin* ]] ;then
+    # forbidden
+    log "someone (${IP}) wants to register ${ID}"
     exit 2
 fi
 
@@ -89,13 +101,15 @@ if [[ ${REQ} = "REGISTRATION" ]]; then
      # phase 1
      generate_challenge     
 
+     # log the registration information in ${FILE}, overwrite any existing registration
+     # so only the last one is valid
      /usr/bin/touch ${FILE} >/dev/null 2>/dev/null
      if [[ -r ${FILE} ]] ; then 
           /usr/bin/echo "ID=${ID}" > $FILE
 	  /usr/bin/echo "ADDR=${IP}" >> $FILE   
           /usr/bin/echo "NONCE=${NONCE}" >> $FILE   
           /usr/bin/echo "CHALLENGE=${CHALLENGE}" >> $FILE   
-	  log "providing a challenge for ${ID}"
+	  log "providing a challenge for ${ID} for registration."
 	  /usr/bin/echo -n "${CHALLENGE}"
 	  exit 0
      fi
@@ -108,47 +122,58 @@ if [[ ${REQ} != "REGISTRATION" ]] ; then
      # load the stored credentials
      if [[ -r ${FILE} ]] ; then
           .  ${FILE}
+     else
+          # no previous registration information is available
+	  log "false request for ${ID} at IP :${IP}"
      fi
 
-     # check if the new request has the same ADDR
+     # check if the new request has the same ADDR as in the stored registration information
      if [[ ${IP} != ${ADDR}  ]] ; then
          # dismiss this request
-	 clean
          log "different IP in phase 2 for user ${ID}"
          exit 4
      fi
 
+     # save the user's PUBKEY in the admin directory
      PUBKEY=${DEST}/${ID}.pubkey.pem
-     # store the pubkey first
+     # store the new pubkey first, before the request is verified
      /usr/bin/echo -n "${KEY}" | /usr/bin/base64 -d > ${PUBKEY}
      
+     # the tmp directory is used for verification, as no user directory exists at this point
      /usr/bin/ln -s ../tmp ${DEST}/${ID}
-     verify_request
-     rm -f ${DEST}/${ID}
-     log "verification of signed request succeeded"
+     if verify_request ; then
+          rm -f ${DEST}/${ID}
+          log "verification of signed request succeeded"
 
-     # split the request
-     OLDIFS="${IFS}"
-     IFS=\:
-     set -- ${REQ} 
-     WID=$1
-     WCHL=$2
-     IFS=${OLDIFS}
+          # split the request
+          OLDIFS="${IFS}"
+          IFS=\:
+          set -- ${REQ} 
+          WID=$1
+          WCHL=$2
+          IFS=${OLDIFS}
 
-     if [[ ${WID} != ${ID} ]] || [[  ${WCHL} != ${CHALLENGE} ]]  ; then
-          # request failed
-	  log "registration failed for user ${ID}"
-	  /usr/bin/echo "none"
-          cleansig
+          if [[ ${WID} != ${ID} ]] || [[  ${WCHL} != ${CHALLENGE} ]]  ; then
+               # request failed
+	       log "registration failed for user ${ID}"
+	       /usr/bin/echo "none"
+               cleansig
+               rm -f ${DEST}/${ID}
+	       exit 3
+          fi
+
+          # create a registration code and store it
+          REGCODE=$(/usr/bin/dd if=/dev/urandom bs=1 count=20 2>/dev/null | /usr/bin/base64 | /usr/bin/cut -c-20 )
+          /usr/bin/echo "REGCODE=${REGCODE}" >> $FILE 
+          log "registration succeeded for user ${ID}"
+          log "--- registration end ---"
+          /usr/bin/echo -n ${REGCODE}
+     else
+          rm -f ${DEST}/${ID}
+          # no valid request, log and be silent to give no indication of failure
+	  log "registration failed for user ${ID} : corrupt/invalid request."
 	  exit 3
      fi
-
-     # create a registration code and store it
-     REGCODE=$(/usr/bin/dd if=/dev/urandom bs=1 count=20 2>/dev/null | /usr/bin/base64 | /usr/bin/cut -c-20 )
-     /usr/bin/echo "REGCODE=${REGCODE}" >> $FILE 
-     log "registration succeeded for user ${ID}"
-     log "--- registration end ---"
-     /usr/bin/echo -n ${REGCODE}
 fi     
 
 cleansig
